version: "3.2"
services:
  reactions:
    build:
      context: .
    ports:
      - "3000"
      - "9229"
    links:
      - redis
    depends_on:
      - redis
    command: "yarn watch"
    secrets:
      - env

  redis:
    image: redis:4.0
  
secrets:
  env:
    file: .env
